#!/usr/bin/env python3
"""
Live demo for the DGX Spark data-analysis agent.

Runs a scripted conversation that walks the five judging criteria, printing what the agent
is doing (which skill it chose, on what arguments, on which engine, and on this call how much
faster the GPU was than the CPU) so an audience can see the autonomy and the speedup rather
than take either on faith.

    python demo_script.py              # full run
    python demo_script.py --prewarm    # run once before the audience arrives
    python demo_script.py --list       # show the steps only
    python demo_script.py --only 3     # one step (useful when rehearsing)
    python demo_script.py --fast       # skip the slowest step

Each step prints its wall-clock time, so a live run can be paced and a rehearsal can find
the slow spots.

--prewarm matters for a live demo: the first time a given query is asked, the agent also runs
it on the CPU to measure the speedup, which adds ~15-25s on a 20M-row file. Prewarming
performs that comparison once up front and fills the cache, so every step of the live demo
shows its speedup immediately.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time

from openai import OpenAI

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from agent_main import Agent, MODEL_NAME, build_client  # noqa: E402

_HERE = os.path.dirname(os.path.abspath(__file__))

# Dataset for the demo. Defaults to a "demo" directory next to this checkout; override with
# DEMO_DATA or --data. Kept free of machine-specific absolute paths so the script is portable.
_default_data = os.path.join(os.path.dirname(_HERE), "benchmark", "demo", "sales_demo.csv")
DATA = os.environ.get("DEMO_DATA", _default_data)

# The deliverable step writes here, so a rehearsal never litters the checkout.
DELIVERABLES_DIR = os.environ.get(
    "DEMO_DELIVERABLES_DIR", os.path.join(_HERE, "deliverables"))

# (title, what the audience should notice, question)
STEPS = [
    (
        "① Finds the data by itself",
        "No file path is given, so the agent decides to call list_datasets and see what is there",
        "Which data files on this server can I analyze?",
    ),
    (
        "② Natural language to full-data statistics",
        "The prompt only asks for a look at the data; the agent picks analyze_dataset by itself "
        "and computes statistics over the full dataset",
        "Take a look at {data} and give me an overall picture",
    ),
    (
        "③ Group-by aggregation (arguments generated by the model)",
        "A plain business request: the agent builds the by and agg arguments itself",
        "What is the total and average revenue by region in {data}? Top 5 groups",
    ),
    (
        "④ Correlation analysis",
        "A relationship question picks corr; watch whether the agent claims causation",
        "Which numeric columns in {data} correlate most strongly with each other, and what does "
        "that mean?",
    ),
    (
        "⑤ Outlier detection (the main GPU scenario)",
        "IQR outlier detection over the full data, reporting the engine that was actually used; "
        "the columns asked about differ from what auto covered in stage 2, which forces a new "
        "tool call",
        "Run the IQR outliers for the revenue and cost columns of {data} on their own, with "
        "counts and shares",
    ),
    (
        "⑥ Failure path: the file does not exist",
        "Robustness: it does not crash and does not guess, it reports the problem "
        "(judging criterion 4)",
        "Analyze {missing_file}",
    ),
    (
        "⑦ No tool call when none is needed",
        "A conceptual question must not trigger a data-analysis tool; this checks the trigger "
        "boundary",
        "Explain what the interquartile range (IQR) is and why it finds outliers",
    ),
    (
        "⑧ Deliverables: results as files you can take away",
        "The earlier stages produce nothing but text in the conversation. Here the agent calls "
        "export_deliverables, which runs the full analysis on the GPU and writes a report (.md), "
        "charts (.svg) and CSV. Watch whether it gives you the file paths: an answer with no "
        "files is not a deliverable.",
        "Analyze revenue in {data} by region and category, then produce a report with charts",
    ),
    (
        "⑨ Multi-step drill-down: five full-data analyses in one session",
        "The most convincing stage of the demo. The agent opens a session with dataset_session "
        "(the data stays resident in GPU memory) and then drills down inside that one session: "
        "first the size of the outlier problem, then two dimensions that narrow it down, then "
        "whether it is only a correlation. Two things to watch: each step's step time is under a "
        "second, because nothing is re-read from disk; and at the end close reports the "
        "comparison for the whole workflow, meaning how long the same five steps would take on "
        "the CPU if every step re-read the file. Progress is held by the system (the plan), so "
        "the agent does not lose its way or forget to close.",
        "Where do the revenue outliers in {data} come from? Find them, drill down to the cause, "
        "and do the whole thing in a session that you release at the end",
    ),
]


def banner(text: str, char: str = "=") -> None:
    print(f"\n{char * 74}\n{text}\n{char * 74}", flush=True)


def prewarm(data_path: str) -> None:
    """Fill the GPU-vs-CPU comparison cache for the queries the demo is about to ask.

    The cache is keyed on file identity + operation + arguments, so warming the demo's exact
    queries is enough to make every live step show its speedup without a pause.
    """
    import skills

    warmups = [
        ("auto", {}),
        ("groupby", {"by": "region", "agg": "revenue:sum,mean"}),
        ("corr", {}),
        ("outliers", {"columns": "revenue,cost"}),
        ("summary", {}),
    ]
    banner("Warming the GPU/CPU comparison cache (run before the audience arrives)")
    print("The first run of each query also runs it on the CPU for comparison; the whole "
          "warmup takes about 1-2 minutes.")
    print("Once warmed, every live step shows its speedup straight away.\n")
    for op, kwargs in warmups:
        started = time.perf_counter()
        # Measure and cache the CPU baseline directly. Going through analyze_dataset would
        # also pay the GPU run, and its arguments would have to match the model's exactly.
        measured = skills.warm_comparison(data_path, op, **kwargs)
        elapsed = time.perf_counter() - started
        if not measured:
            print(f"  {op:<9} {elapsed:6.1f}s   (measurement failed, skipped)")
        else:
            print(f"  {op:<9} {elapsed:6.1f}s   CPU baseline "
                  f"{measured['baseline_seconds']:.2f}s")
    print("\nWarmup done.")
    print(f"cache entries: {len(skills._COMPARISON_CACHE)}")

    # Warm the session path too: the drill-down step should not pause to measure a CPU
    # baseline on stage. Opening once and closing measures the whole workflow in one go.
    banner("Warming the session workflow (the five-step drill-down in stage 9)")
    t0 = time.perf_counter()
    opened = json.loads(skills.dataset_session(operation="open", file_path=data_path,
                                               goal="find the revenue outliers and drill down "
                                                    "to the cause"))
    if not opened.get("success"):
        print(f"  session open failed: {opened.get('error')}  (stage 9 will be slower, "
              f"the demo still runs)")
        return
    sid = opened.get("session_id")
    plan = opened.get("plan") or {}
    print(f"  session {sid} open: {opened.get('rows'):,} rows, "
          f"resident {opened.get('resident_mb')}MB, plan of {plan.get('total_steps')} steps"
          f" (kind {plan.get('kind')})")
    for s in plan.get("steps", []):
        args = s.get("args") or {}
        extra = "  " + " ".join(f"{k}={v}" for k, v in args.items()) if args else ""
        print(f"    {s['step']+1}. {s['op']}{extra}")
    for step in plan.get("steps", []):
        skills.dataset_session(operation="analyze", session_id=sid, op=step["op"], **{
            k: v for k, v in (step.get("args") or {}).items()
            if k in ("by", "agg", "columns", "top_k")})
    closed = json.loads(skills.dataset_session(operation="close", session_id=sid))
    wc = closed.get("workflow_comparison") or {}
    print(f"  workflow comparison cached: {wc.get('session_total_seconds')}s vs "
          f"CPU {wc.get('naive_cpu_seconds')}s = {wc.get('speedup_x')}x"
          f"  ({time.perf_counter() - t0:.1f}s wall)")


def main() -> int:
    ap = argparse.ArgumentParser(description="scripted live demo")
    ap.add_argument("--only", type=int, help="run a single step by number")
    ap.add_argument("--list", action="store_true", help="list steps and exit")
    ap.add_argument("--fast", action="store_true", help="skip the slowest step")
    ap.add_argument("--prewarm", action="store_true",
                    help="fill the GPU/CPU comparison cache, then exit")
    ap.add_argument("--data", default=DATA, help=f"dataset path (default {DATA})")
    args = ap.parse_args()

    if args.list:
        for i, (title, notice, q) in enumerate(STEPS, 1):
            print(f"{i}. {title}\n"
                  f"   question: {q.format(data=args.data, missing_file='<nonexistent>.csv')}\n"
                  f"   watch for: {notice}")
        return 0

    # Shadow the module-level default rather than mutating it; a local is enough here and
    # avoids a `global` declaration after DATA has already been read as a default value.
    data_path = args.data
    if not os.path.exists(data_path):
        print(f"[warn] demo dataset not found: {data_path}")
        print("       generate it with memory_ceiling_test.generate(), or pass --data")

    if args.prewarm:
        prewarm(data_path)
        return 0

    client: OpenAI = build_client()
    agent = Agent(client, verbose=True)

    selected = STEPS if args.only is None else [STEPS[args.only - 1]]
    timings = []

    banner(f"DGX Spark data-analysis agent — live demo  (model={MODEL_NAME})")
    print(f"dataset: {data_path}")
    print(f"{len(selected)} stages; the time each one took is listed at the end")

    for step_no, (title, notice, question) in enumerate(selected, 1):
        banner(f"{title}\n[watch for] {notice}", "-")
        question = question.format(
            data=data_path,
            missing_file=os.path.join(_HERE, "no_such_file_xyz.csv"),
        )
        print(f"User: {question}\n")
        started = time.perf_counter()
        try:
            answer = agent.run(question)
        except Exception as exc:
            print(f"[demo aborted] {type(exc).__name__}: {exc}")
            return 1
        elapsed = time.perf_counter() - started
        timings.append((title, elapsed))
        print(f"--- agent answer ---\n{answer}\n")
        print(f"[this stage took {elapsed:.1f}s]")

    banner("End of demo — time per stage")
    total = 0.0
    for title, secs in timings:
        total += secs
        print(f"  {secs:7.1f}s   {title}")
    print(f"  {total:7.1f}s   total")
    return 0


if __name__ == "__main__":
    sys.exit(main())